### ISSUE TITLE
Pick a Blog / Static Site Engine

### ISSUE THREAD

**Issue by aviflombaum** [railshotway/therailshotway.com#1]
@JoseFarias Want to pick a blog / static site engine? I love Middleman but I'm down for anything.

**Comment by josefarias** [comment]
Been a while since I've used Middleman but I have no problems with it. Let's use it.

What's your vision for the blog? I think we should start publishing content to get the hype up even before we finish the book. Might be a good way to gauge interest and promote the book (& other future endeavors like the companion site, if they come to light).
